# Generated by Django 4.2 on 2023-04-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер машины')),
                ('make', models.CharField(max_length=50, verbose_name='Производство')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.CharField(max_length=50, verbose_name='Год производства')),
            ],
        ),
    ]
