# Generated by Django 4.2 on 2023-04-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Unknown', max_length=30, verbose_name='Бренд'),
        ),
    ]
